services:
  mysql:
    image: mysql:5.7
    container_name: "db.mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${MYSQL_PORT}:3306"
  adminer:
    image: adminer
    container_name: "db.adminer"
    ports:
      - "${ADMINER_PORT}:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
